package common

// used file to save some common values

// go example names
const (
	Arrays                = "array"
	AtomicCounterExpl     = "atomiccounter"
	Base                  = "base"
	Channel               = "chan"
	ChannelBuffer         = "chanbuf"
	ChannelCloseExpl      = "chan-close"
	ChannelDirection      = "chandirect"
	ChannelRangeExpl      = "chan-range"
	ChannelSync           = "chansync"
	Constants             = "const"
	Closure               = "closure"
	CronJob               = "cronjob"
	DeferExpl             = "defer"
	Embed                 = "embed"
	ErrorExpl             = "error"
	ForExpl               = "for"
	FuncExpl              = "function"
	Generics              = "generics"
	GoRoutineExpl         = "goroutine"
	HelloWorld            = "helloworld"
	IfEl                  = "ifel"
	InterfaceExpl         = "interface"
	IpAddrExpl            = "ipaddr"
	JsonExpl              = "json"
	MapExpl               = "map"
	MethodExpl            = "method"
	MutexExpl             = "mutex"
	NetExpl               = "net"
	NonBlockSelectExpl    = "non-block-chan-ops"
	PanicExpl             = "panic"
	Pointer               = "pointer"
	Pongo2Expl            = "pongo2"
	RangeExpl             = "range"
	RateLimitingExpl      = "ratelimit"
	RecoverExpl           = "recover"
	Recursion             = "recur"
	RegExpExpl            = "regexp"
	Return                = "return"
	SelectExpl            = "select"
	ShiftExpl             = "shift"
	Slices                = "slice"
	SortingExpl           = "sort"
	SortByFunc            = "sortfunc"
	StatefulGoroutineExpl = "stateful-goroutine"
	StringFormat          = "strformat"
	StringFunc            = "strfunc"
	StringRune            = "str"
	StructExpl            = "struct"
	SwitchBranch          = "switch"
	TextTemp              = "texttemp"
	TimeExpl              = "time"
	TimeOut               = "timeout"
	TimerExpl             = "timer"
	TickerExpl            = "ticker"
	UnitTestExpl          = "ut"
	Values                = "values"
	Variables             = "vars"
	WaitGroupExpl         = "waitgroup"
	WorkerExpl            = "worker"
	TimeProcessExpl       = "timeproc"
	RandExpl              = "rand"
	StrNumExpl            = "strnum"
	UrlExpl               = "url"
	SHAExpl               = "sha"
	Base64Expl            = "base64"
	FileReadExpl          = "fileread"
	FileWriteExpl         = "filewrite"
	FilePath              = "filepath"
)
